### ISSUE TITLE
laravel 5.2 使用中间件报错

### ISSUE THREAD

**Issue by Jasongzj** [liyu001989/dingo-serializer-switch#3]
环境：laravel 5.2
在 app/Http/Kernel.php 中定义了中间件。
```
protected $middleware = [
    \Liyu\Dingo\SerializerSwitch::class,
];
```

路由文件：
```
$api->version('v1', [
    'namespace' => 'App\Http\Controllers\Api',
    'middleware' => 'serializer:array',
], function($api) {});
```

访问接口时报错
```
{
    "message": "Undefined offset: 1",
    "status_code": 500,
    "debug": {
        "line": 22,
        "file": "/home/vagrant/Code/million-angels/vendor/liyu/dingo-serializer-switch/src/SerializerSwitch.php",
        "class": "ErrorException",
        "trace": [
            "#0 /home/vagrant/Code/million-angels/vendor/liyu/dingo-serializer-switch/src/SerializerSwitch.php(22): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/home/vagrant/C...', 22, Array)",
            "#1 /home/vagrant/Code/million-angels/vendor/liyu/dingo-serializer-switch/src/SerializerSwitch.php(34): Liyu\\Dingo\\SerializerSwitch->getDriver('data_array')",
            "#2 [internal function]: Liyu\\Dingo\\SerializerSwitch->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#3 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)",
            "#4 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#5 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#6 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)",
            "#7 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#8 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
            "#9 /home/vagrant/Code/million-angels/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#10 /home/vagrant/Code/million-angels/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#11 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#12 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)",
            "#13 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#14 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
            "#15 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#16 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
            "#17 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#18 /home/vagrant/Code/million-angels/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#19 /home/vagrant/Code/million-angels/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#20 {main}"
        ]
    }
}
```

**Comment by liyu001989** [comment]
5.2 没测试过，为啥不升级到5.5 ，5.2 都不维护了。

安装的哪个版本，你可以去代码里面调试一下

**Comment by Jasongzj** [comment]
我也想用5.5的  只是公司的环境限制，还在用php5.6
我看了一下代码，问题出现在这
```
protected function getDriver($name)
{
    // 这里 array_key_exists 返回一个true，导致出现了上面的错误
    $name = array_key_exists($name, $this->drivers) ?: 'data_array';
    return $this->drivers[$name];
}
```

**Comment by Jasongzj** [comment]
0.2.1 解决了这个问题，但是要求php 7.0... 我自己改一下实现~感谢！
